const products =[
    {
     "id": 5131,
     "name": "OVAL",
     "description": "Transform your space with this Single Color OVAL shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 4\"L x 4\"W x 7\"H, this OVAL shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, this salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the OVAL SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 8,
     "weight": 2,
     "length": 4,
     "width": 4,
     "height": 7,
     "sale_price": 1610,
     "regular_price": 2300,
     "Category": "Signature Lamps"
    },
    {
     "id": 5139,
     "name": "CYLINDER",
     "description": "Transform your space with this Single Color CYLINDER shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\"L x 6\"W x 6\"H, this CYLINDER shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the CYLINDER SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 11,
     "weight": 2.5,
     "length": 4,
     "width": 4,
     "height": 7,
     "sale_price": 1740,
     "regular_price": 2200,
     "Category": "Signature Lamps"
    },
    {
     "id": 5146,
     "name": "MOON BALL",
     "description": "Transform your space with this Single Color MOON BALL salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\" in diameter, this MOON BALL salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the MOON BALL SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 7,
     "weight": 4.5,
     "length": 6,
     "width": 6,
     "height": 6,
     "sale_price": 2205,
     "regular_price": 3150,
     "Category": "Signature Lamps"
    },
    {
     "id": 5151,
     "name": "GLOBE",
     "description": "Transform your space with this Single Color GLOBE shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\" in diameter, this GLOBE shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the GLOBE SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 6,
     "weight": 4.5,
     "length": 6,
     "width": 6,
     "height": 6,
     "sale_price": 1925,
     "regular_price": 2750,
     "Category": "Signature Lamps"
    },
    {
     "id": 5157,
     "name": "LEAF",
     "description": "Transform your space with this Single Color LEAF shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 3\"L x 5\"W x 8\"H, this LEAF shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the LEAF SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 8,
     "weight": 3,
     "length": 3,
     "width": 5,
     "height": 8,
     "sale_price": 1540,
     "regular_price": 2200,
     "Category": "Signature Lamps"
    },
    {
     "id": 5160,
     "name": "NATURAL",
     "description": "Transform your space with this Single Color NATURAL shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 4\"L x 4\"W x 8\"H, this NATURAL shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the NATURAL SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 15,
     "weight": 2.5,
     "length": 4,
     "width": 4,
     "height": 8,
     "sale_price": 1740,
     "regular_price": 2200,
     "Category": "Signature Lamps"
    },
    {
     "id": 5166,
     "name": "RAINDROP",
     "description": "Transform your space with this Single Color RAINDROP salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 4\"L x 4\"W x 7\"H, this RAINDROP shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the RAINDROP SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 10,
     "sale_price": 1610,
     "regular_price": 2300,
     "Category": "Signature Lamps"
    },
    {
     "id": 5171,
     "name": "FIRE BOWL",
     "description": "Transform your space with this Single Color FIRE BOWL salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\"L x 6\"W x 7\"H, this FIRE BOWL salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the FIRE BOWL SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 6,
     "weight": 3.5,
     "length": 6,
     "width": 6,
     "height": 7,
     "sale_price": 2240,
     "regular_price": 3200,
     "Category": "Signature Lamps"
    },
    {
     "id": 5179,
     "name": "DIAMOND",
     "description": "Transform your space with this Single Color DIAMOND shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\"L x 6\"W x 6\"H, this DIAMOND shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the DIAMOND SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 7,
     "weight": 3,
     "length": 5,
     "width": 5,
     "height": 5,
     "sale_price": 1925,
     "regular_price": 2750,
     "Category": "Signature Lamps"
    },
    {
     "id": 5445,
     "name": "BOWL",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 10,
     "sale_price": 2450,
     "regular_price": 3500,
     "Category": "Premium Lamps"
    },
    {
     "id": 5480,
     "name": "GLOBE",
     "description": "Transform your space with this Multi Color <strong>GLOBE<\/strong> shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\nMeasuring 3.7 inches in diameter, this <strong>GLOBE<\/strong> shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you're looking to add some color to your space or just enjoy the benefits of negative ions, this multicolor salt lamp is the perfect choice.\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the MULTICOLOR GLOBE SHAPED LAMP to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 12,
     "weight": 1,
     "length": 3.7,
     "width": 3.7,
     "height": 3.7,
     "sale_price": 980,
     "regular_price": 1400,
     "Category": "Multicolor Lamps"
    },
    {
     "id": 5481,
     "name": "DICE",
     "description": "Transform your space with this Multi Color <strong>DICE<\/strong> shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\nMeasuring 3.5\"L x 3.5\"W x 3.5\"H, this <strong>DICE<\/strong> shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you're looking to add some color to your space or just enjoy the benefits of negative ions, this multicolor salt lamp is the perfect choice.\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the MULTICOLOR DICE SHAPED LAMP to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 8,
     "weight": 1.4,
     "length": 3.5,
     "width": 3.5,
     "height": 3.5,
     "sale_price": 910,
     "regular_price": 1300,
     "Category": "Multicolor Lamps"
    },
    {
     "id": 5546,
     "name": "LANTERN",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 10,
     "weight": 3.5,
     "length": 6,
     "width": 6,
     "height": 10,
     "sale_price": 2345,
     "regular_price": 3350,
     "Category": "Premium Lamps"
    },
    {
     "id": 5547,
     "name": "WATERMELON",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 2,
     "sale_price": 2170,
     "regular_price": 3100,
     "Category": "Premium Lamps"
    },
    {
     "id": 5548,
     "name": "CURLY",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 6,
     "weight": 1.7,
     "length": 5,
     "width": 5,
     "height": 8.5,
     "sale_price": 2240,
     "regular_price": 3200,
     "Category": "Premium Lamps"
    },
    {
     "id": 5549,
     "name": "HEXAGONE",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 9,
     "weight": 3,
     "length": 5,
     "width": 5,
     "height": 8,
     "sale_price": 3350,
     "regular_price": 4850,
     "Category": "Premium Lamps"
    },
    {
     "id": 5550,
     "name": "ZIG ZAG",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 3,
     "weight": 3,
     "length": 5,
     "width": 5,
     "height": 8,
     "sale_price": 3350,
     "regular_price": 4850,
     "Category": "Premium Lamps"
    },
    {
     "id": 5551,
     "name": "DUSTBIN",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 10,
     "weight": 1.7,
     "length": 5,
     "width": 5,
     "height": 6,
     "sale_price": 2450,
     "regular_price": 3500,
     "Category": "Premium Lamps"
    },
    {
     "id": 5552,
     "name": "SPHERE",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 4,
     "weight": 2,
     "length": 5,
     "width": 5,
     "height": 6,
     "sale_price": 2870,
     "regular_price": 4100,
     "Category": "Premium Lamps"
    },
    {
     "id": 5553,
     "name": "ROUND",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 2,
     "weight": 1.7,
     "length": 5,
     "width": 5,
     "height": 6,
     "sale_price": 2450,
     "regular_price": 3500,
     "Category": "Premium Lamps"
    },
    {
     "id": 5554,
     "name": "BIRDS",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 0,
     "stock": 0,
     "weight": 2,
     "length": 5,
     "width": 5,
     "height": 6,
     "sale_price": 3395,
     "regular_price": 4850,
     "Category": "Premium Lamps"
    },
    {
     "id": 5555,
     "name": "HORSE",
     "description": "Transform your space with the breathtaking beauty of our Laser Cutting Basket Salt Lamps. Handcrafted from pure Himalayan salt, these lamps are not only stunning to look at but also offer a range of health benefits.\\n\\nWith their intricate laser-cut designs, these salt lamps make the perfect addition to any room in your home, office, or workplace. Their soft glow creates a relaxing ambiance, helping to reduce stress and promote concentration, making them ideal for use in a meditation room or as a night light.\\n\\nIncorporating a Himalayan salt lamp into your daily life is a simple and effective way to improve your health. The negative ions released by the salt help to purify the air, reducing allergens and promoting overall well-being. Whether you use it as an aromatherapy salt lamp or simply for its decorating qualities, this basket salt lamp is sure to add a touch of style and serenity to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add our Laser Cutting Basket Salt Lamp to your home today and experience the many benefits of Himalayan salt. Whether you're looking for a wellness accessory, a natural air purifier, or simply a beautiful home d?cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 1,
     "weight": 2,
     "length": 5,
     "width": 5,
     "height": 6,
     "sale_price": 3395,
     "regular_price": 4850,
     "Category": "Premium Lamps"
    },
    {
     "id": 5684,
     "name": "FLOWER",
     "description": "Transform your space with this Single Color FLOWER shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 6\" in diameter, this FLOWER shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, this salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the FLOWER SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 1,
     "stock": 8,
     "weight": 4.5,
     "length": 6,
     "width": 6,
     "height": 6,
     "sale_price": 2205,
     "regular_price": 3150,
     "Category": "Signature Lamps"
    },
    {
     "id": 6197,
     "name": "BLACK NATURAL",
     "description": "Transform your space with this Single Color NATURAL shaped salt lamp from The Salt Craft, a unique and stylish lighting solution that also offers a range of health benefits. Made from pure Himalayan salt, this salt lamp is not only a beautiful home d�cor accessory but also a natural air purifier and negative ion generator.\\n\\nMeasuring 4\"L x 4\"W x 8\"H, this NATURAL shaped salt lamp is the perfect size for your home, office, or study. Its calming and soothing glow creates a relaxing ambiance, making it an ideal choice for stress relief and meditation. Whether you�re looking to add some color to your space or just enjoy the benefits of negative ions, thi salt lamp is the perfect choice.\\n\\nIncorporating this salt lamp into your daily life is a simple and effective way to promote healthy living. Not only does it cleanse the air, but it also helps to improve concentration and promotes a sense of well-being. Whether you use it as a night light or simply as a decoration, this lamp is sure to add a touch of style to any room.\\n\\nSo why settle for a boring lamp when you can have a unique and beneficial lighting solution? Add the NATURAL SHAPED SALT LAMP to your home today and experience the many benefits of Himalayan salt. Whether you�re looking for a wellness accessory, a natural air purifier, or simply a beautiful home d�cor item, this salt lamp has you covered.",
     "stock_check": 0,
     "stock": 0,
     "weight": 2.5,
     "length": 4,
     "width": 4,
     "height": 8,
     "sale_price": 1540,
     "regular_price": 2200,
     "Category": "Signature Lamps"
    }
   ];

   export default products;